#!/usr/bin/perl

my $IDX = "index.html";

my ($version, $devprod) = @ARGV;

$version =~ s/.*?(\d+[\.\d]+)\..*/$1/;

die "usage: $0 version" unless $version =~ /^[\d.]+\w+$/;

system "git checkout gh-pages" and die $!;

open FILE, "<$IDX" or die "Cannot open $IDX";
my $data = join '', <FILE>;
close FILE;

my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);
my $date = sprintf "%02d/%02d/%d", $mon+1, $mday, $year+1900;

$data =~ s/<!--NEWS-->.*?<!--\/NEWS-->/repnews()/se;

if(defined $devprod and $devprod =~ /(dev)|(alpha)|(beta)/) {
    $data =~ s@<!--DEV-->.*?<!--/DEV-->@repdev()@se;
} else {
    $data =~ s@<!--STABLE-->.*?<!--/STABLE-->@repstable()@se;
    $data =~ s@<!--DEV-->.*?<!--/DEV-->@<!--DEV-->\n<!--/DEV-->@s;
}

open FILE, ">$IDX" or die "Cannot open $IDX";
print FILE $data;
close FILE;

system "git commit -a -mversion-bump" and die $!;
system "git push origin gh-pages" and die $!;
system "git checkout master" and die $!;

##################################################
sub repnews {
##################################################
    return <<EOT
<!--NEWS-->
<FONT SIZE=-1><B>$date:</B></FONT><BR>
<FONT COLOR='#8dbf85'><B>Released</B></FONT> version <A HREF=http://search.cpan.org/CPAN/authors/id/M/MS/MSCHILLI/Log-Log4perl-$version.tar.gz>$version</A><BR>
<!--/NEWS-->
EOT
}

##################################################
sub repstable {
##################################################
    return <<EOT
<!--STABLE-->
<FONT SIZE=-1><B>Stable Release ($date)</B></FONT>
<B><A HREF=http://search.cpan.org/CPAN/authors/id/M/MS/MSCHILLI/Log-Log4perl-$version.tar.gz>Log-Log4perl-$version.tar.gz</A></B>
<!--/STABLE-->
EOT
}

##################################################
sub repdev {
##################################################
    return <<EOT
<!--DEV-->
<FONT SIZE=-1><B>Development Release ($date)</B></FONT>
<B><A HREF=http://search.cpan.org/CPAN/authors/id/M/MS/MSCHILLI/Log-Log4perl-$version.tar.gz>Log-Log4perl-$version.tar.gz</A></B>
<!--/DEV-->
EOT
}

__END__
cp $1 /home/groups/l/lo/log4perl/htdocs/releases
cd /home/groups/l/lo/log4perl/htdocs/releases
tar zxfv $1
dir=`echo $1 | sed 's/.tar.gz//'`
rm -f Log-Log4perl
ln -s $dir Log-Log4perl
upddoc

<!--NEWS-->
<FONT SIZE=-1><B>08/08/2002:</B></FONT><BR>
<FONT COLOR='#8dbf85'><B>Released</B></FONT> version 0.21 to <A HREF=http://www.cpan.org/authors/id/MSCHILLI/Log-Log4perl-0.21.tar.gz>CPAN</A>.<BR>
<!--/NEWS-->

<hr noshade="noshade" />
<FONT SIZE=+1 COLOR='#fc464f'><B>Documentation:</B></FONT><P>
<B><A HREF=/releases/Log-Log4perl/docs/html/Log/Log4perl.html>Manual</A></B><BR>
<B><A HREF=/releases/Log-Log4perl/Changes>Changes</A></B>
<hr noshade="noshade" />
<FONT SIZE=+1 COLOR='#fc464f'><B>Download:</B></FONT><P>
<!--STABLE-->
<FONT SIZE=-1><B>Stable Release (07/23/2002)</B></FONT>
<B><A HREF=/releases/Log-Log4perl-0.21.tar.gz>Log-Log4perl-0.21.tar.gz</A></B>
<!--/STABLE-->

