#!/usr/local/bin/perl
###########################################
# cvskwexp - check if we have $Log... instances 
# Mike Schilli, 2004 (m@perlmeister.com)
###########################################
use warnings;
use strict;

use File::Find;

find(sub {
         return if /cvskwexp/;
         my $file = $_;
         # print "Examining $_\n";
         open FILE, "<$_" or die "Cannot open $_";
         while(<FILE>) {
             die "$file: $_" if /\$\s*Log.*\$/;
         }
         close FILE;
     }, ".");
