#!/usr/local/bin/perl
###########################################
# release -- Release this module
# Mike Schilli, 2002 (m@perlmeister.com)
###########################################
# RELEASE checklist:
# * Update log4perl project download page
#   Upload to upload.sourceforge.net
#   https://sourceforge.net/project/admin/newrelease.php?package_id=52323&group_id=56939
# * Notify log4perl-devel
# * Check 5.00503 compatibility
###########################################

use warnings;
use strict;

    # Available at http://perlmeister.com/scripts
use lib "$ENV{HOME}/perl-modules";
use ModDevUtils;
use ExtUtils::Manifest;
use Test::Pod;
use Test::More;
use File::Find;
use Test::Harness;

my($devprod) = @ARGV;

system("adm/cvskwexp") and die "\$Log... detected";

    # Check if all the POD complies with the standard
my $admdir = ".";
$admdir = "adm" if -d "lib";
runtests("$admdir/podok");

{
    no strict;
    *ModDevUtils::main_pm_file = sub { "lib/Log/Log4perl.pm" };
}

ModDevUtils::release(0) or exit 0;

my @missing = ExtUtils::Manifest::manicheck();

if(@missing) {
    die "Manifest check failed, missing files: @missing";
}

my $ball = ModDevUtils::tarball_name();

my $target = "mschilli,log4perl\@web.sourceforge.net:htdocs";

# now on CPAN
# system("scp $ball $target/releases/$ball");

    # Win32 package
print "Building Win32 ppm distribution ...\n";
system("cd adm; ./mkppm; tar zcfv ppm.tgz ppm");

print "Copying ppm to log4perl.sourceforge.net ...\n";
system("scp adm/ppm/* $target/ppm");

system("adm/sourceforge/updindex $ball");

system("scp adm/sourceforge/www/index.html $target");

__END__
