#!/usr/bin/perl
###########################################
# release -- Release this module
# Mike Schilli, 2002 (m@perlmeister.com)
###########################################
# RELEASE checklist:
# * Update log4perl project download page
#   Upload to upload.sourceforge.net
#   https://sourceforge.net/project/admin/newrelease.php?package_id=52323&group_id=56939
# * Notify log4perl-devel
# * Check 5.00503 compatibility
###########################################

use warnings;
use strict;

    # Available at http://perlmeister.com/scripts
use lib "$ENV{HOME}/perl-modules";
use ModDevUtils;
use Test::Pod;
use Test::More;
use File::Find;
use Test::Harness;

my($devprod) = @ARGV;

system("adm/cvskwexp") and die "\$Log... detected";

    # Check if all the POD complies with the standard
my $admdir = ".";
$admdir = "adm" if -d "lib";
runtests("$admdir/podok");

ModDevUtils::release(0) or exit 0;

my $ball = ModDevUtils::tarball_name();
print "Copying $ball to log4perl.sourceforge.net ...\n";
system("scp $ball log4perl.sourceforge.net:");
print "Releasing it on sourceforge.net ...\n";

if(defined $devprod and $devprod eq "dev") {
    print "Running ssh log4perl.sourceforge.net bin/rel $ball $devprod\n";
    system("ssh log4perl.sourceforge.net bin/rel $ball $devprod\n");
    print "No Win32 package is being prepared for development releases\n";
} else {
    print "Running ssh log4perl.sourceforge.net bin/rel\n";
    system("ssh log4perl.sourceforge.net bin/rel $ball\n");
    # Win32 package
    print "Building Win32 ppm distribution ...\n";
    system("cd adm; ./mkppm; tar zcfv ppm.tgz ppm");

    print "Copying ppm to log4perl.sourceforge.net ...\n";
    system("scp adm/ppm.tgz log4perl.sourceforge.net:");
    print "Releasing it on sourceforge.net ...\n";
    system("ssh log4perl.sourceforge.net bin/relppm\n");
}
