#!/usr/bin/perl
###########################################
# Release the PPM3 packages
# Mike Schilli, 2002 (m@perlmeister.com)
###########################################
use warnings;
use strict;

# Win32 package
system("rm -f ppm3; mv ppm ppm3; tar zcfv ppm3.tgz ppm3");

print "Copying ppm to log4perl.sourceforge.net ...\n";
system("scp ppm3.tgz log4perl.sourceforge.net:");

print "Releasing it on sourceforge.net ...\n";
system("ssh log4perl.sourceforge.net bin/relppm3\n");
