#!/usr/bin/perl
######################################################################
# adm/sfupd -- 2003, Mike Schilli <m@perlmeister.com>
######################################################################
# Update Net::Amazon on Sourceforge
######################################################################
use strict;
use warnings;

my  $VERSION = "0.01";
our $CVSVERSION = '$Revision: 1.6 $';

use Net::Sourceforge;
#use Log::Log4perl qw(:easy);
#Log::Log4perl->easy_init($DEBUG);

my $sf = Net::Sourceforge->new(
    sf_user         => 'mschilli',
    sf_package_id   => 52323,
    sf_group_id     => 56939,
);

$sf->readin_password();

$sf->ftp_upload();
$sf->sf_release();

__END__

=head1 NAME

    adm/sfupd - Update Net::Amazon on Sourceforge

=head1 SYNOPSIS

    adm/sfupd

=head1 DESCRIPTION

Takes the first tarball it finds and pushes it up to the
Log::Log4perl project page on sourceforge.net

Uses Net::Sourceforge from Mike's script archive 

    http://perlmeister.com/scripts

=head1 EXAMPLES

  $ adm/sfupd

=head1 LEGALESE

Copyright 2004 by Mike Schilli, all rights reserved.
This program is free software, you can redistribute it and/or
modify it under the same terms as Perl itself.

=head1 AUTHOR

2003, Mike Schilli <m@perlmeister.com>
