#!/usr/bin/perl
use warnings;
use strict;

    # Can be obtained from http://perlmeister.com/scripts
use ModDevUtils;

{
    no strict;
    *ModDevUtils::main_pm_file = sub { "lib/Log/Log4perl.pm" };
}

ModDevUtils::update_readme();
