#!/usr/bin/perl
###########################################
# release -- Release this module
# Mike Schilli, 2002 (m@perlmeister.com)
###########################################
use warnings;
use strict;

    # Available at http://perlmeister.com/scripts
use lib "$ENV{HOME}/perl-modules";
use ModDevUtils;

ModDevUtils::release() or exit 0;

my $ball = ModDevUtils::tarball_name();
print "Copying $ball to log4perl.sourceforge.net ...\n";
system("scp $ball log4perl.sourceforge.net:");
print "Releasing it on sourceforge.net ...\n";
system("ssh log4perl.sourceforge.net bin/rel $ball\n");

# Win32 package
print "Building Win32 ppm distribution ...\n";
system("make clean; perl Makefile.PL BINARY_LOCATION=\"http://log4perl.sourceforge.net/ppm/Log-Log4perl.tar.gz\"; make; make ppd; tar zcf Log-Log4perl.tar.gz blib");
print "Patching Log-Log4perl.ppd ...\n";
open FILE, "<Log-Log4perl.ppd" or die "Cannot open Log-Log4perl.ppd";
my $data = join '', <FILE>;
close FILE;
$data =~ s#<OS NAME=".*?" />#<OS NAME="MSWin32" />#;
$data =~ s#<ARCHITECTURE NAME=".*?" />#<ARCHITECTURE NAME="MSWin32-x86-multi-thread" />#;

open FILE, ">Log-Log4perl.ppd" or die "Cannot open Log-Log4perl.ppd";
print FILE $data;
close FILE;

print "Copying ppm to log4perl.sourceforge.net ...\n";
system("scp Log-Log4perl.tar.gz log4perl.sourceforge.net:");
system("scp Log-Log4perl.ppd log4perl.sourceforge.net:");
print "Releasing it on sourceforge.net ...\n";
system("ssh log4perl.sourceforge.net bin/relppm\n");
